### ISSUE TITLE
JOSS Review: community guidelines

### ISSUE THREAD

**Issue by wcjochem** [orbisgis/lczexplore#13]
Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support?

Please edit the README to provide this information.

[openjournals/joss-reviews/issues#5445](https://github.com/openjournals/joss-reviews/issues/5445)

**Comment by MGousseff** [comment]
Thank you very much for the improvement. I added to the .github a CONTRIBUTING.md and linked it to a CODE_OF_CONDUCT.md (the classical one inspired from Mozilla). I'm very grateful for all the improvements you suggested, it really helps me update my practices. Let me know if it is OK before I close the issue.

**Comment by wcjochem** [comment]
Thanks for the addition. I'll make this complete now.
